### ISSUE TITLE
Help :c

### ISSUE THREAD

**Issue by italorecife** [Nuitka/NUITKA-Utilities#42]
```
NUITKA v0.6.9rc3 on Python 3.8.3 (win32) is compiling 'teste.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=teste-38-win32-64.json

Nuitka-Plugins:INFO: hinted-mods: 'hinted-mods' is adding the following options:
Nuitka-Plugins:INFO: hinted-mods: Enabling Nuitka plugin 'numpy' as needed.
Traceback (most recent call last):
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 160, in main
    activatePlugins()
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 577, in activatePlugins
    _addActivePlugin(plugin_class, args=True)
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 70, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
  File "C:\Users\italo\Desktop\bt\NUITKA-Utilities-master\hinted-compilation\hinted-mods.py", line 284, in __init__
    lateActivatePlugin(plugin_name, option_values)
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 589, in lateActivatePlugin
    _addActivePlugin(getPluginClass(plugin_name), args=True, force=True)
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 70, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
TypeError: __init__() got an unexpected keyword argument 'sklearn'
```

or 

```
NUITKA v0.6.8rc5 on Python 3.8.3 (win32) is compiling 'teste.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=teste-38-win32-64.json

Traceback (most recent call last):
  File "nuitka-hints.py", line 106, in <module>
    main()
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 60, in main
    Options.parseArgs()
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\Options.py", line 41, in parseArgs
    is_nuitka_run, options, positional_args, extra_args = parseOptions()
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\OptionParsing.py", line 790, in parseOptions
    _considerPluginOptions()
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\OptionParsing.py", line 763, in _considerPluginOptions
    addUserPluginCommandLineOptions(parser=parser, filename=arg[14:])
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 629, in addUserPluginCommandLineOptions
    plugin_class = loadUserPlugin(filename)
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 506, in loadUserPlugin
    user_plugin_module = importFile(plugin_filename)
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 490, in importFile
    return importFilePy3NewWay(filename)
  File "C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py", line 449, in importFilePy3NewWay
    spec.loader.exec_module(user_plugin_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\italo\Desktop\bt\NUITKA-Utilities-master\hinted-compilation\hinted-mods.py", line 38, in <module>
    from nuitka.plugins.Plugins import lateActivatePlugin, getActivePlugins
ImportError: cannot import name 'lateActivatePlugin' from 'nuitka.plugins.Plugins' (C:\Users\italo\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\plugins\Plugins.py)
```

**Comment by kayhayen** [comment]
The sklearn option was giving, but not used, and as such now causes problems. I will push a fix to the Utilities repo soon.

**Comment by kayhayen** [comment]
Done, let me know if the master work branch there works better now.
