### ISSUE TITLE
getSharedLibrarySuffix is missing

### ISSUE THREAD

**Issue by derrickberg-dev** [Nuitka/NUITKA-Utilities#47]
https://github.com/Nuitka/NUITKA-Utilities/blob/3a48d69f85dfbc94136517e85507b92aef1d4b74/hinted-compilation/get-hints.py#L43

I changed it to `from nuitka.utils.Importing import getSharedLibrarySuffix`
 which then resulted in an error while processing my script..
```
ValueError: invalid literal for int() with base 10: '288nv53'
Traceback (most recent call last):
  File ".\get-hints.py", line 546, in <module>
    myexit(lname, jname, False)  # transform logfile to JSON file
  File ".\get-hints.py", line 333, in myexit
    call_analyzer(ifile, text, import_calls, import_files, trace_logic)
  File ".\get-hints.py", line 196, in call_analyzer
    call_analyzer(f, text, import_calls, import_files, trace_logic)
  File ".\get-hints.py", line 196, in call_analyzer
    call_analyzer(f, text, import_calls, import_files, trace_logic)
  File ".\get-hints.py", line 240, in call_analyzer
    hasFilenameExtension(res_file, getSharedLibrarySuffix())  # a shared module!
TypeError: getSharedLibrarySuffix() missing 1 required positional argument: 'preferred'
```

**Comment by kayhayen** [comment]
The import was moved during 0.6.9 development, but I failed to update this, but now did.
