### ISSUE TITLE
Hinted compilation with nuitka 0.6.9

### ISSUE THREAD

**Issue by cvpython** [Nuitka/NUITKA-Utilities#50]
I have installed nuitka 0.6.9.1 and use nuitka-utilities from the master branch.
When I try to compile with the hinted approach (`python get-hints.py script.py`) I have the following error:
```
Traceback (most recent call last):
  File "get-hints.py", line 43, in <module>
    from nuitka.utils.Utils import getSharedLibrarySuffix
ImportError: cannot import name 'getSharedLibrarySuffix' from 'nuitka.utils.Utils'
```

Are there nutika-utilities compatible with nuitka 0.6.9.1 ?

Here are some characteristics of my installation:
> 
> 0.6.9.1
> Python: 3.7.6 (default, Jan  8 2020, 19:59:22) 
> OS: Linux
> Arch: x86_64

**Comment by cvpython** [comment]
Thanks @kayhayen  for your reply !

I have tried the new hinted compilation scripts.
Unfortunately, there is still error:

```
NUITKA v(0, 6, 9, 3) on Python 3.7.8 (linux) is compiling 'hello.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=hello-37-linux-64.json

Nuitka-Plugins:INFO: hinted-mods: 'hinted-mods' is adding the following options:
Nuitka-Plugins:INFO: hinted-mods: Enabling Nuitka plugin 'numpy' as needed.
Traceback (most recent call last):
  File "/home/anaconda3/envs/exe_pandas/lib/python3.7/site-packages/nuitka/__main__.py", line 196, in <module>
    main()
  File "/home/anaconda3/envs/exe_pandas/lib/python3.7/site-packages/nuitka/__main__.py", line 161, in main
    activatePlugins()
  File "/home/anaconda3/envs/exe_pandas/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 600, in activatePlugins
    _addActivePlugin(plugin_class, args=True)
  File "/home/anaconda3/envs/exe_pandas/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 73, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
  File "/home/Documents/Developpement/Python_Work/NUITKA/hinted-mods.py", line 283, in __init__
    lateActivatePlugin(plugin_name, option_values)
  File "/home/anaconda3/envs/exe_pandas/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 610, in lateActivatePlugin
    _addActivePlugin(getPluginClass(plugin_name), args=True, force=True)
  File "/home/anaconda3/envs/exe_pandas/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 73, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
TypeError: __init__() got an unexpected keyword argument 'matplotlib'
```

The script hello.py that I try to compile is only:
```
import pandas
print("hello word !")
```

Here are some information about my installation:
```
0.6.9.3
Python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
Executable: /home/anaconda3/envs/exe_pandas/bin/python
OS: Linux
Arch: x86_64
```

**Comment by kayhayen** [comment]
Yes, that plugin usage may still be broken, I will look into it.
