### ISSUE TITLE
Trouble with hinted compilation

### ISSUE THREAD

**Issue by deajan** [Nuitka/NUITKA-Utilities#9]
Hi Jorj,

It's been awhile, I see you did great stuff in the meantime :)
I just tried your hinted compilation, and it seems that get-hints.py does not find PySimpleGUI as import, maybe because I use ```import PySimpleGUI.PySimpleGUI as sg``` which looks to your program like a repetition ?
Source of my program is https://github.com/deajan/smartd_pyngui

Any tests I should make ?

Btw, get-hints.py detects tkinter... Why not use --plugin=tkinter on nuitka-hints.py in that case ?

Best regards.

**Comment by JorjMcKie** [comment]
Hi Orsiris,
good to see you again in these chats! BTW is your first name of Egypt origin (linguistics / etymology is one of my hobbies)?

Ha! You found a bug in the hinting logic. Which I thought I had sufficiently addressed:
If an exception occurs during an import, hinting skips the rest, instead of just recording the exception ....

In my case, PySimpleGUI is being found, if its import is put before the Crypto imports (which fail on my computer).
That shouldn't happen though (any more), so I will need to look into that hinting logic again ...

**Comment by JorjMcKie** [comment]
Ah, and you need the current version of tk-inter plugin, which knows not only tkinter / Tkinter, but also PySimpleGUI.
The tkinter module will be detected anyway by the hinter of course, but the plugin must insert this TK/TCL library detection code (Windows) also, when PySimpleGUI is encountered.

**Comment by deajan** [comment]
I already ship my TK/TCL code (remember, I came up with this in the first place :))
Does that mean that I'll have duplicated code when using hints compilation ?

**Comment by JorjMcKie** [comment]
No, only those 2 lines, which ensure ``os.environ["TCL_LIBRARY"]`` is valid, are inserted in front of hte ``import tkinter`` **and** in fornt of ``import PySimpleGUI``.

I re-checked the **_hinter_** code, and it looks and works fine with me. Only if an unhandled import exception occurs, the JSON file is incomplete (which it should then be!).

**Comment by JorjMcKie** [comment]
A bit more on the ``get-hints.py`` logic:
* It creates a new Python source modules which consists of Kay's hinter logic as a stub in front of ``yourscript.py``. This new script is then started via `subprocess`. The stub logic produces a log file of all executed imports done while ``yourscript.py`` is executing.
* After end of the script, the logfile is take and converted into a JSON format (removing duplicate entries and fitting each import call to its result via a recursive analysis).
* Because ``yourscript.py`` may use things like multiprocessing, more than one logfile may have been created. Those need to be gathered and combined before the JSON file can be created.
* The corresponding compilation then uses a user plugin, which takes the JSON file to generate ``--enable-plugin`` and ``--recurse-to`` parameters on the fly. So any of these should no longer be required for the compile command line.

**Comment by deajan** [comment]
Got to update my PySimpleGUI import, now my program gets compiled using nuitka-hints.

Still, the program fails in the end, because nuitka-hints drops most of Cryptodome (pycryptodomex) packages that vanilla Nuitka (current develop) now ships out of the box.

Compilation:
```
python nuitka-hints.py smartd_pyngui.py
NUITKA is compiling 'smartd_pyngui.py' with these options:
 --standalone
 --python-flag=nosite
 --remove-output
 --experimental=use_pefile
 --recurse-none
 --disable-dll-dependency-cache
 --user-plugin=hinted-mods.py=smartd_pyngui-3.7.3-win32-32.json

Nuitka:INFO: 'hinted-mods.py' is adding the following options:
Nuitka:INFO: --enable-plugin=tk-inter
Nuitka:INFO: --enable-plugin=enum-compat
Nuitka:INFO:
Nuitka:INFO: Requested Nuitka to recurse to 140 modules.
Nuitka:INFO:
Nuitka:INFO:User plugin 'hinted-mods.py' loaded.
Nuitka:INFO:Injecting plug-in based post load code for module 'enum':
Nuitka:INFO:    Monkey patching "enum" for compiled '__new__' methods.
Nuitka:INFO:Injecting plug-in based pre load code for module 'tkinter':
Nuitka:INFO:    Need to make sure we set environment variables for TCL.
Nuitka:INFO: drop sysconfig (in distutils)
Nuitka:INFO: drop perfmon
Nuitka:INFO: drop win32evtlogutil
Nuitka:INFO: drop servicemanager
Nuitka:INFO: drop getopt
Nuitka:INFO: drop PySimpleGUI27 (in PySimpleGUI)
Nuitka:INFO: drop _cpuid_c (in Cryptodome.Util)
Nuitka:INFO: drop _raw_aes (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_aesni (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_arc2 (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_blowfish (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_cast (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_cbc (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_cfb (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_ctr (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_des (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_des3 (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_ecb (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_ocb (in Cryptodome.Cipher)
Nuitka:INFO: drop _raw_ofb (in Cryptodome.Cipher)
Nuitka:INFO: drop _BLAKE2s (in Cryptodome.Hash)
Nuitka:INFO: drop _strxor (in Cryptodome.Util)
Nuitka:INFO: drop _ghash_portable (in Cryptodome.Hash)
Nuitka:INFO: drop Cryptodome.Protocol (in Cryptodome)
Nuitka:INFO: drop _Salsa20 (in Cryptodome.Cipher)
Nuitka:INFO: drop _scrypt (in Cryptodome.Protocol)
Nuitka:INFO: drop _MD5 (in Cryptodome.Hash)
Nuitka:INFO: drop _SHA256 (in Cryptodome.Hash)
Nuitka:INFO: drop _SHA1 (in Cryptodome.Hash)
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:WARNING:Didn't recurse to '_collections_abc', apparently not used.
Nuitka:WARNING:Didn't recurse to '_compat_pickle', apparently not used.
Nuitka:WARNING:Didn't recurse to '_compression', apparently not used.
Nuitka:WARNING:Didn't recurse to '_weakrefset', apparently not used.
Nuitka:WARNING:Didn't recurse to 'base64', apparently not used.
Nuitka:WARNING:Didn't recurse to 'bisect', apparently not used.
Nuitka:WARNING:Didn't recurse to 'bz2', apparently not used.
Nuitka:WARNING:Didn't recurse to 'codecs', apparently not used.
Nuitka:WARNING:Didn't recurse to 'collections.abc', apparently not used.
Nuitka:WARNING:Didn't recurse to 'copy', apparently not used.
Nuitka:WARNING:Didn't recurse to 'copyreg', apparently not used.
Nuitka:WARNING:Didn't recurse to 'ctypes._endian', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email._encoded_words', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email._parseaddr', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email._policybase', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.base64mime', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.charset', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.contentmanager', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.encoders', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.errors', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.headerregistry', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.iterators', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.message', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.mime.nonmultipart', apparently not used.
Nuitka:WARNING:Didn't recurse to 'email.utils', apparently not used.
Nuitka:WARNING:Didn't recurse to 'encodings', apparently not used.
Nuitka:WARNING:Didn't recurse to 'enum', apparently not used.
Nuitka:WARNING:Didn't recurse to 'genericpath', apparently not used.
Nuitka:WARNING:Didn't recurse to 'heapq', apparently not used.
Nuitka:WARNING:Didn't recurse to 'hmac', apparently not used.
Nuitka:WARNING:Didn't recurse to 'importlib._bootstrap', apparently not used.
Nuitka:WARNING:Didn't recurse to 'importlib._bootstrap_external', apparently not used.
Nuitka:WARNING:Didn't recurse to 'json.decoder', apparently not used.
Nuitka:WARNING:Didn't recurse to 'json.encoder', apparently not used.
Nuitka:WARNING:Didn't recurse to 'linecache', apparently not used.
Nuitka:WARNING:Didn't recurse to 'locale', apparently not used.
Nuitka:WARNING:Didn't recurse to 'lzma', apparently not used.
Nuitka:WARNING:Didn't recurse to 'operator', apparently not used.
Nuitka:WARNING:Didn't recurse to 'posixpath', apparently not used.
Nuitka:WARNING:Didn't recurse to 'queue', apparently not used.
Nuitka:WARNING:Didn't recurse to 'quopri', apparently not used.
Nuitka:WARNING:Didn't recurse to 'selectors', apparently not used.
Nuitka:WARNING:Didn't recurse to 'signal', apparently not used.
Nuitka:WARNING:Didn't recurse to 'stat', apparently not used.
Nuitka:WARNING:Didn't recurse to 'string', apparently not used.
Nuitka:WARNING:Didn't recurse to 'tkinter.commondialog', apparently not used.
Nuitka:WARNING:Didn't recurse to 'tkinter.constants', apparently not used.
Nuitka:WARNING:Didn't recurse to 'tkinter.dialog', apparently not used.
Nuitka:WARNING:Didn't recurse to 'tokenize', apparently not used.
Nuitka:WARNING:Didn't recurse to 'traceback', apparently not used.
Nuitka:WARNING:Didn't recurse to 'urllib', apparently not used.
Nuitka:WARNING:Didn't recurse to 'uu', apparently not used.
Nuitka:WARNING:Didn't recurse to 'weakref', apparently not used.
Nuitka:INFO: Now copying tk libraries from 'C:\\Python37-32\\tcl\\tk8.6'.
Nuitka:INFO: Now copying tkinter libraries from 'C:\\Python37-32\\tcl\\tcl8.6'.
Nuitka:INFO: Compile time 269 seconds.
```

Execution:
```
smartd_pyngui.exe
Traceback (most recent call last):
  File "C:\GIT\smartd_pyngui\smartd_pyngui\smartd_pyngui.dist\smartd_pyngui.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\GIT\smartd_pyngui\smartd_pyngui\smartd_pyngui.dist\scrambledconfigparser\__init__.py", line 5, in <module scrambledconfigparser>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\GIT\smartd_pyngui\smartd_pyngui\smartd_pyngui.dist\scrambledconfigparser\scrambledconfigparser.py", line 24, in <module scrambledconfigparser.scrambledconfigparser>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\GIT\smartd_pyngui\smartd_pyngui\smartd_pyngui.dist\Cryptodome\Cipher\__init__.py", line 27, in <module Cryptodome.Cipher>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\GIT\smartd_pyngui\smartd_pyngui\smartd_pyngui.dist\Cryptodome\Cipher\_mode_ecb.py", line 35, in <module Cryptodome.Cipher._mode_ecb>
  File "C:\GIT\smartd_pyngui\smartd_pyngui\smartd_pyngui.dist\Cryptodome\Util\_raw_api.py", line 299, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win32.pyd': [WinError 126] Le module spécifié est introuvable, Trying '_raw_ecb.pyd': [WinError 126] Le module spécifié est introuvable
```

Anything that can be done to resolve that issue ?

**Comment by JorjMcKie** [comment]
Damn ... that's the curse of the logic used in ``hinted-mods.py``:
It rejects (drops) everything not contained in the JSON file (or declared acceptable by some other plugin), and therefore import not recognizable by the hinter will be dropped.

Unfortunately, I have no access to the ``ImplicitImports.py`` list. What is named there would be the solution.

I am thinking about how to resolve this (like making the decision in implicit imports dictionary-based or the like). But I have currently no graps around this.

As a shortcut solution, I could quickly right a user plugin, that declares everything acceptable ...

Just tell me how urgent your stuff is. That plugin is really no big deal: less than 30 minutes for sure.

**Comment by JorjMcKie** [comment]
I am still concerned, why PySimpleGUI is dropped as well.
Something is still wrng with that JSON file ...

**Comment by deajan** [comment]
I do resolve this by copying *.pyd files from Cryptodome package including folder structure, so there's really no urgency for me :)

The point is finding best way to honor the ImplicitImports list.
Why not do the following (pseudo bad coffee code) in your hints logic:
```
import nuitka.plugins.standard.ImplictImports as ImplictImports 

# Do your logic stuff
imp = ImplictImports()

for module in hints_gathered_modules:
    keep_module =  imp.getImplicitImports(module)
    if keep_module in (hints_gathered_modules):
         # Don't remove it from list
```

**Comment by deajan** [comment]
> I am still concerned, why PySimpleGUI is dropped as well.
> Something is still wrng with that JSON file ...

Worry not, PySimpleGUI27 did get dropped because I use python3 so that's pretty okay :)

**Comment by JorjMcKie** [comment]
Ah, good there is no rush on your side.
To your suggestion:
One of my first thoughts. **HOWEVER:** In my ``hinted-mods.py`` I only get module / package **_names_** delivered and not modules, as it is required by the implicit imports plugin.

So this idea will unfortunately not work. I can also neither recreate the module back from its name :-(

What I am considering is rewriting ``ImplicitImports.py``, such that it contains a dictionary which delivers a list of import names per module name. The funny thing is that these implicit import decisions actually already do not use the Nuitka module **object**, but instead its full_name ...

That hypothetical dictionary would then be the thing to import in other plugins ...

**Comment by deajan** [comment]
**still being quite a Python n00b** ...I see... Accessing a dictionnary without any further calls....
Then it would probably be nice to put the dictionnary in a separate file from the ImplictImports logic, just so edits become easy.

**Comment by JorjMcKie** [comment]
Might be.
I am still not 100% certain, that a static type of data would really be able to perfectly reflect all possible situations.
I mean, you would have to change this, if you change or upgrade a Qt installation for example. Seems to me that some sort of programmatic reaction to this type of thing will always be necessary, and a piece of program like ``ImplicitImports.py`` is not at all the worst thing to have for this ...
This plugin could look around when being loaded (``__init__py``) and update stuff accordingly. It would still be easy enough to maintain the data inside that plugin.

I think I will try out a few options and see what would be a good solution ...

**Comment by deajan** [comment]
I've retried hinted compilation today after a couple of months.
I still cannot get my bigger programs to work because of missing imports.

I've tried to manually specify which imports I want to keep, but without success.
Eg:
`
c:\python37-64\python.exe nuitka-hints.py --follow-import-to=pywin32_bootstrap myscript.py
[...]
Nuitka:INFO:drop pywin32_bootstrap
[...]
`

Is there any specific syntax I should use to override drops from the hints-mods.py plugin ?

Best regards.

**Comment by deajan** [comment]
With patches for #19 and #20, I was finally able to compile my biggest programs I work on since a year or so, using hinted compilation.
Those programs use pysimplegui, tkinter, multiprocessing, pywin32, wmi, requests, requests_pcks12, openssl, pycrpytodomex, psutil, threading and a couple of home made packages, so they are "real world" cases for dev-ops.

I've patched my toolchain to allow both standard nuitka and hinted compilation, here are the results:

Standard compile time = 31 min, 274M
Hinted compile time = 27 min, 227M

Once I've stripped other things down (using the same technique I patched one-file-maker.py with), I have two NSIS installers of 31M and 25M.

**So in my real world case, I observe a gain of 20% size and 14% compile time.**

Thanks @JorjMcKie for this awesome tool.

As a side note, I had to add a `--test` parameter for some of those programs so they don't actually perform some of the tasks they are supposed to when using get-hints.py.

**Comment by JorjMcKie** [comment]
Wow,
this is a very nice feedback - thank you!
And a special thank you for your help smoothing all those rough edges.

I am nevertheless a bit disappointed, that the savings percentages ares not higher 😉.
But I know you to be a sysadmin-aware person, so you probably applied a lot of optimization before even using hinting.

> As a side note, I had to add a --test parameter for some of those programs so they don't actually perform some of the tasks they are supposed to when using get-hints.py.

You are certainly aware that the JSON file produced in ``get-hints`` only needs to contain a complete set of the imports ever done by the application. So, the stuff being compiled by nuitka-hints does not really need to be identical to that executed under ``get-hints`` - as long as that one condition is met.
One could even manually maintain the JSON file ...

**Comment by deajan** [comment]
I'd like to improve compile times more too.
I optimized my programs for simplicity.
I think I could break down my packages into subpackages that I import per program instead if a whole package, to have lesser imports per program. Would that work (a bit) ?

I also have Big imports because of requests_pkcs12, which I cannot optimize.

Unfortunately, I use mingw which I cannot cache using clcache, so compiling speed won't improve, even if m'y programs share a lot.

Any ideas where else I could look ?
Compiling on a octocore 3.6ghz is still 26 min, and I compile alot... ;)

Best regards.

**Comment by JorjMcKie** [comment]
> I think I could break down my packages into subpackages that I import per program instead if a whole package, to have lesser imports per program. Would that work (a bit) ?

That would work a whole lot! I made a test with PySimpleGUI. When I compile this package (as you know it is pure, pure Python) as a pyd extension, the compile times for all apps using it go down significantly - at least relatively.

So what I am doing is turning as much stuff into Python extension modules as I can. The time savings are quite significant. And the good thing is, that those extension modules will be imported preferrably when living in the same folder ...

**Comment by deajan** [comment]
Well I've tried to improve my compilation times a bit more, and realized that the `--remove-output` option of nuitka-hints.py prevented the scons build cache from working.
I've made PR #23 that removes the option.

So here we go:

**drumrolls**

| Compilation Method | File size |
|---|---|
| Nuitka --standalone | 274M |
| nuitka-hints.py | 227M |


| Compilation Method | Other optimizations | Compile time|
|---|---|---|
| nuitka --standalone | None | 31 min|
| nuitka-hints.py | None | 27 min|
| nuitka-hints.py | Precompiled PySimpleGUI module | 21 min|
| nuitka-hints.py | Precompiled PySimpleGUI module, scons cache first pass | 21 min|
| nuitka-hints.py | Precompiled PySimpleGUI module, scons cache second pass | 16 min|

Since I compile a couple of programs, both in 32 and 64 bits in this example, prebuilding PySimpleGUI saves me another 5-6 minutes.

**Comment by deajan** [comment]
@JorjMcKie How about pre-compiling the whole site-packages directory ?
The only drawback I see is it needs recompilation after a pip upgrade.

**Comment by JorjMcKie** [comment]
Wow, you are an extremist 😂!
But seriously, the big hitters should really be taken under consideration ... or the top used 20% or something.

BTW I have never tried to make an extension module from a **_package_**, i.e. something having an ``__init__.py``. Did you do that before?

**Comment by JorjMcKie** [comment]
When thinking of obvious candidates like numpy, one would end up with a shared lib representing the **_whole package_**, from which hinted compilation would no longer be able to subselect parts of: whenever hinting encounters a shared library as target of some import statement, it will readily have to accept it, because it can neither know if it is legally there (contained in the DLL), nor be able to break out unused parts of that DLL.

**Comment by deajan** [comment]
> Wow, you are an extremist 😂!
AYBABTU !!!

I also asked Kay about a more elegant solution, ie, adding a C file cache to Nuitka, which obviously is nicer and less way less drawbacks, see https://github.com/Nuitka/Nuitka/issues/121#issuecomment-571605004 ;)

I'd happily (try to) implement that feature in Nuitka.

**Comment by JorjMcKie** [comment]
Yes I remember Kay mentioning this.
I never looked at the compile time number profile. But my gutt feeling is that avoiding repeated generation of always the same C code is a good thing, but only "die halbe Miete".
The other part is compiling that stuff. So it probably would be ideal to store the compiled (object) file and match it with the corresponding Python source.

Hope I am not talking complete nonsense, but couldn't we create a hash code for a module and see if a compiled object for it exists in some database? If yes, take it without re-generating the C code and without recompiling it ...

**Comment by deajan** [comment]
That's what I talked about, a sha256sum of a package / module (being a rolling sum of all the files in the package except of course .py[co] files).
Then keep the compiled object, put it's sum  together with a date into a DB (eg sqlite ?)
If a sum of a package already exists in the DB... profit ;)
Use a LRU algorithm to evict old objects (let's suppose we keep 1GB or whatever arbitrary value we want).

There's just that integer that changes between two programs using the same package, so for now there's no way to have a global database, even though this would be a must have.
